name: pokemon
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.13.5
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter
  go_router: ^12.1.3
  google_fonts: ^6.1.0
  http: ^1.1.2
  intl: any
  json_annotation: ^4.8.1
  multi_select_flutter: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
